quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('question/<int:question_id>', views.question, name='question'),
    path('leaderboard/<int:player_group>', views.leaderboard, name='leaderboard'),
]

siteterre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

quiz/models.py
import json
from django.db import models

class PlayerGroup(models.Model):
    player_group = models.IntegerField(primary_key=True, db_index=True)

    def __str__(self):
        return f'{self.player_group}'

class Player(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50)
    player_group = models.ForeignKey(PlayerGroup, on_delete=models.CASCADE) # Each player is associated with a group
    score = models.IntegerField(default=0)
    lives = models.IntegerField(default=3)

    def __str__(self):
        return f'{self.username} from {self.player_group}'

    def increase_score(self, increment):
        self.score += increment

    def decrease_lives(self, decrement):
        self.lives -= decrement

class Question(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.CharField(max_length=300)
    choice_1 = models.CharField(max_length=300)
    choice_2 = models.CharField(max_length=300)
    choice_3 = models.CharField(max_length=300)
    choice_4 = models.CharField(max_length=300)
    answer = models.CharField(max_length=500, default='[]')
    explanation = models.CharField(max_length=1000, default='')

    def __str__(self):
        return self.question

    # Create a json string to make an answer list
    def set_answer(self, answer_list):
        self.answer = json.dumps(answer_list)

    # Use json to transform the list in string form to a usable list
    def get_answer(self):
        return json.loads(self.answer)

    # Check if the given answer is part of the answer list
    def verify_answer(self, given_answer):
        correct_answer = self.get_answer()
        return given_answer in correct_answer

quiz/forms.py
from django.forms import ModelForm
from quiz.models import Player

class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['username', 'player_group']
        labels = {
                    'username': 'Nom d\'utilisateur',
                    'player_group': 'Groupe'
                    }

quiz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import PlayerGroup, Player, Question
from .forms import PlayerForm
from random import shuffle

def home(request):
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            player_group = form.cleaned_data['player_group']
            new_player = Player(username=username, player_group=player_group)
            new_player.save()
            request.session['player_id'] = new_player.id
        return redirect(reverse('quiz:question', args=[Question.objects.order_by('id').first().id]))
    form = PlayerForm()
    context = {
                'title': 'Accueil',
                'form': form
                }
    return render(request, 'quiz/home.html', context)

def question(request, question_id):
    last_question_id = Question.objects.order_by('id').reverse()[0].id
    question = Question.objects.get(id=question_id)
    choices = [
                question.choice_1,
                question.choice_2,
                question.choice_3,
                question.choice_4
                ]
    shuffle(choices)
    question_answer = question.get_answer()
    player = Player.objects.get(id=request.session['player_id'])
    if request.method == 'POST':
        given_answer = request.POST.get('choice')
        if given_answer in question_answer:
            player.increase_score(4)
        else:
            player.decrease_lives(1)
        player.save()
        messages.info(request, f'{question.explanation}')
        if question_id == last_question_id or player.lives == 0:
            return redirect(reverse('quiz:leaderboard', args=[player.player_group]))
        else:
            return redirect(reverse('quiz:question', args=[question_id + 1]))
    context = {
                'title': 'Question',
                'question': Question.objects.get(id=question_id),
                'question_choices': choices,
                'score': player.score,
                'lives': player.lives
                }
    return render(request, 'quiz/question.html', context)

def leaderboard(request, player_group):
    if player_group == 0:
        players_in_group = Player.objects.order_by('score').reverse().all()
        context = {
                    'title': 'Classement general',
                    'player_group': 'General',
                    'players_in_group': players_in_group
                    }
        return render(request, 'quiz/leaderboard.html', context)
    else:
        player_group = PlayerGroup.objects.get(player_group=player_group)
        players_in_group = player_group.player_set.order_by('score').reverse().all()
        context = {
                    'title': f'Classement du groupe {player_group}',
                    'player_group': player_group,
                    'players_in_group': players_in_group
                    }
        return render(request, 'quiz/leaderboard.html', context)

quiz/templates/quiz/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <title>
            {% block title %}
                {% if title %}
                    {{ title }}
                {% endif %}
            {% endblock %}
        </title>
    </head>

    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand text-success" href="{% url 'quiz:home' %}">Accueil</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'quiz:leaderboard' player_group=0 %}">Classement general</a>
                </div>
            </div>
        </nav>
        <br>
    {% endblock %}

    {% block content %}
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            {% block app_content %}
            {% endblock %}
        </div>
    {% endblock %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% endblock %}
</html>

quiz/templates/quiz/csv_form.html
{% extends 'admin/base.html'%}

{% block branding %}
<h1>Quiz Admin</h1>
{% endblock %}
{% block content %}
    <div>
        <form action="." method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}

                <button type="submit">Ajouter Fichier</button>
        </form>
    </div>
    <br>
{% endblock %}

quiz/templates/quiz/group_change_list.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="create_new_group">Créer un nouveau groupe</a>
    <br>
    {{ block.super }}
{% endblock %}

quiz/templates/quiz/home.html
{% extends "quiz/base.html" %}
{% load widget_tweaks %}

{% block app_content %}
    <form action="." method="POST">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
        {% for field in form.visible_fields %}
            <div class="form-row">
                <div class="col-5">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            </div>
            <br>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Commencer</button>
    </form>
{% endblock %}

quiz/templates/quiz/leaderboard.html
{% extends "quiz/base.html" %}

{% block app_content %}
    {% if player_group == "General" %}
        <h1>Classement general</h1>
    {% else %}
        <h1>Classement du groupe {{ player_group }}</h1>
    {% endif %}
    {% for player in players_in_group %}
        <br>
        <p>{{ player.username }}: {{ player.score }}</p>
    {% endfor %}
{% endblock %}

quiz/templates/quiz/new_group_form.html
{% extends 'admin/base.html' %}

{% block branding %}
<h1>Quiz Admin</h1>
{% endblock %}
{% block content %}
    <div>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}

                <button type="submit">Créer groupe</button>
        </form>
    </div>
{% endblock %}

quiz/templates/quiz/question.html
{% extends "quiz/base.html" %}

{% block app_content %}
    <h3 class="float-left text-primary">Pointage: {{ score }}</h3>
    <h3 class="float-right text-danger">Vies: {{ lives }}</h3>
    <br>
    <br>
    <br>
    <h3>{{ question.question }}</h3>
    <br>
    <form action="{% url 'quiz:question' question_id=question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question_choices %}
        {% if choice != '...' %}
            <div class="radio">
                <label><input type="radio" name="choice" value="{{ choice }}"> {{ choice }}</label>
            </div>
            <br>
        {% endif %}
        {% endfor %}
        <br>
        <button type="submit" name="button" class="btn btn-primary btn-lg">Valider</button>
        <br>
    </form>
{% endblock %}

quiz/templates/quiz/question_change_list.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import_csv">Importer Fichier CSV</a>
    <br>
    {{ block.super }}
{% endblock %}